apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bcttest1
  description: bcttest1
  annotations:
    github.com/project-slug: 'backstage/backstage'
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: website
  lifecycle: production
  owner: user:bct