---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DataSourceT2-db
  description: DataSourceT2
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DataSourceT1-db
  description: DataSourceT1
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DataSourceT1-db
  description: DataSourceT1
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: USERDB-db
  description: USERDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TDBName-db
  description: TDBName
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Test_DS-db
  description: Test_DS
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: RESERVDB-db
  description: RESERVDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: RESERVDB-db
  description: RESERVDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DatasourceT1-db
  description: DatasourceT1
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ROUTING-db
  description: ROUTING
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DBINPUT-db
  description: DBINPUT
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DataSourceT3-db
  description: DataSourceT3
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: RESERVDB-db
  description: RESERVDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DatasourceT2-db
  description: DatasourceT2
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DBInput-db
  description: DBInput
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DatasourceT3-db
  description: DatasourceT3
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: PR-Datasource-db
  description: PR-Datasource
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TestDataSource-db
  description: TestDataSource
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: DataSourceT1-db
  description: DataSourceT1
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: SIMPLERROUTEDB-db
  description: SIMPLERROUTEDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: USERDB-db
  description: USERDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: RESERVDB-db
  description: RESERVDB
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: TLOGMON-db
  description: TLOGMON
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
---					
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ROUTING-db
  description: ROUTING
spec:
  type: database
  owner: iib
  system: Security-Our-Broker-demo5a
  
