apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-schematron-Schematron_Main.msgflow
  title: com/aon/qmp/schematron/Schematron_Main.msgflow - 1
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_Cleansing.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_Cleansing.msgflow - 2
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_Preprocessing.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_Preprocessing.msgflow - 3
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_SaveTradeRequest.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_SaveTradeRequest.msgflow - 4
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_RetrieveAssigne.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_RetrieveAssignedInfo.msgflow - 5
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_ReplayPostProce.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_ReplayPostProcessing.msgflow - 6
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-services-GetPersonByUserId.msgflow
  title: com/aon/qmp/services/GetPersonByUserId.msgflow - 7
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_Main.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_Main.msgflow - 8
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  
  dependsOn:
  - resource:BRK.WPG.REQUEST.GENERAL-mq

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-broker-qmp-replay-ReplayComplete_Main.msgflow
  title: com/aon/broker/qmp/replay/ReplayComplete_Main.msgflow - 9
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-services-Country.msgflow
  title: com/aon/qmp/services/Country.msgflow - 10
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_CreateTradeRequ.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_CreateTradeRequest.msgflow - 11
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-schematron-Schematron_ValidationPreproces.msgflow
  title: com/aon/qmp/schematron/Schematron_ValidationPreprocessing.msgflow - 12
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-utils-crm-CrmNotification.msgflow
  title: com/aon/qmp/utils/crm/CrmNotification.msgflow - 13
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-broker-qmp-replay-ReplayError_Main.msgflow
  title: com/aon/broker/qmp/replay/ReplayError_Main.msgflow - 14
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-schematron-Schematron_PreProcessing.msgflow
  title: com/aon/qmp/schematron/Schematron_PreProcessing.msgflow - 15
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_MapToTradeRequest.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_MapToTradeRequest.msgflow - 16
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-services-GetBizpackSectionsCovered.msgflow
  title: com/aon/qmp/services/GetBizpackSectionsCovered.msgflow - 17
  description: |
     This subflow calls the CoverInformation REST service in QMP to find out what are the sections covered from the Policy Message. (http://@bat-dns@/ws/service/coverage/extractcoveredlist)  This service is implemented for Business Pack Products ONLY.   It accepts an ACORD Policy message, and returns a string containing the sections covered.   For example, a successful response will look like this,  &lt;sectionsCovered success=&quot;true&quot;&gt;FIRE,GLASS&lt;/sectionsCovered&gt;  Failed response will look like this  &lt;sectionsCovered success=&quot;false&quot;&gt;Some error&lt;/sectionsCovered&gt;
  sda.se/summary: |
     This subflow calls the CoverInformation REST service in QMP to find out what are the sections covered from the Policy Message. (http://@bat-dns@/ws/service/coverage/extractcoveredlist)  This service is implemented for Business Pack Products ONLY.   It accepts an ACORD Policy message, and returns a string containing the sections covered.   For example, a successful response will look like this,  &lt;sectionsCovered success=&quot;true&quot;&gt;FIRE,GLASS&lt;/sectionsCovered&gt;  Failed response will look like this  &lt;sectionsCovered success=&quot;false&quot;&gt;Some error&lt;/sectionsCovered&gt;
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_FindSectionsCov.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_FindSectionsCovered.msgflow - 18
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-broker-qmp-replay-Replay_Process.msgflow
  title: com/aon/broker/qmp/replay/Replay_Process.msgflow - 19
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: com-aon-qmp-traderequest-TradeRequest_UpdateQsAndCrea.msgflow
  title: com/aon/qmp/traderequest/TradeRequest_UpdateQsAndCreateTrade.msgflow - 20
spec:
  type: service
  lifecycle: production
  owner: iib
  system: testJoinSubflows3  

  # providesApis:
  #  - artist-api
---
