---					
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: TEST1-mq
  # description: $escapeTool.html($!datasource.dataSourceName)
spec:  
  type: openapi
  lifecycle: production
  # this ideally should be an argument
  # type: mq - ideally we can have an option for non REST services
  owner: iib
  system: testAggregate1
  definition:
    $text: https://github.com/someproject/openapi.yaml

